//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapURL
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLData
    {
        public System.Guid ID { get; set; }
        public string url { get; set; }
        public bool Processed { get; set; }
        public string result { get; set; }
        public System.DateTime tsAdded { get; set; }
        public Nullable<System.DateTime> tsProcessed { get; set; }
        public Nullable<bool> Mined { get; set; }
        public Nullable<System.DateTime> MinedDate { get; set; }
        public string Game { get; set; }
        public Nullable<System.DateTime> DrawingDate { get; set; }
    }
}
